export interface AITool {
  tool_name: string;
  domain: string;
  category: string;
  vendor: string;
  risk_level: "low" | "medium" | "high";
  is_approved: boolean;
  cost_per_seat?: number;
  suggested_alternative?: string;
}

export const aiToolsRegistry: AITool[] = [
  { tool_name: "ChatGPT", domain: "chatgpt.com", category: "chat", vendor: "OpenAI", risk_level: "medium", is_approved: false, cost_per_seat: 20, suggested_alternative: "Claude" },
  { tool_name: "Sora", domain: "sora.com", category: "video ai", vendor: "OpenAI", risk_level: "medium", is_approved: false },
  { tool_name: "Claude", domain: "claude.ai", category: "chat", vendor: "Anthropic", risk_level: "medium", is_approved: false, cost_per_seat: 20 },
  { tool_name: "Google Gemini", domain: "gemini.google.com", category: "chat", vendor: "Google", risk_level: "medium", is_approved: false },
  { tool_name: "Google AI Studio", domain: "aistudio.google.com", category: "chat", vendor: "Google", risk_level: "medium", is_approved: false },
  { tool_name: "Google AI", domain: "ai.google.com", category: "chat", vendor: "Google", risk_level: "medium", is_approved: false },
  { tool_name: "DeepSeek", domain: "deepseek.com", category: "chat", vendor: "DeepSeek", risk_level: "high", is_approved: false },
  { tool_name: "Grok", domain: "x.ai", category: "chat", vendor: "xAI", risk_level: "medium", is_approved: false },
  { tool_name: "Perplexity AI", domain: "perplexity.ai", category: "chat", vendor: "Perplexity", risk_level: "medium", is_approved: false },
  { tool_name: "Meta AI", domain: "meta.ai", category: "chat", vendor: "Meta", risk_level: "high", is_approved: false },
  { tool_name: "Microsoft Copilot", domain: "copilot.microsoft.com", category: "chat", vendor: "Microsoft", risk_level: "medium", is_approved: true },
  { tool_name: "Microsoft Teams Copilot", domain: "teams.microsoft.com", category: "enterprise productivity", vendor: "Microsoft", risk_level: "low", is_approved: true },
  { tool_name: "Microsoft 365 Copilot", domain: "outlook.office365.com", category: "enterprise productivity", vendor: "Microsoft", risk_level: "low", is_approved: true },
  { tool_name: "Mistral AI", domain: "mistral.ai", category: "chat", vendor: "Mistral", risk_level: "medium", is_approved: false },
  { tool_name: "Le Chat", domain: "chat.mistral.ai", category: "chat", vendor: "Mistral", risk_level: "medium", is_approved: false },
  { tool_name: "Groq", domain: "groq.com", category: "api", vendor: "Groq", risk_level: "high", is_approved: false },
  { tool_name: "Poe", domain: "poe.com", category: "chat", vendor: "Quora", risk_level: "medium", is_approved: false },
  { tool_name: "Qwen AI", domain: "qwen.ai", category: "chat", vendor: "Alibaba", risk_level: "high", is_approved: false },
  { tool_name: "Pi", domain: "pi.ai", category: "chat", vendor: "Inflection", risk_level: "medium", is_approved: false },
  { tool_name: "Cohere", domain: "dashboard.cohere.com", category: "ai platform", vendor: "Cohere", risk_level: "medium", is_approved: true },
  { tool_name: "Together AI", domain: "together.ai", category: "ai platform", vendor: "Together AI", risk_level: "medium", is_approved: false },
  { tool_name: "Fireworks AI", domain: "fireworks.ai", category: "ai platform", vendor: "Fireworks AI", risk_level: "medium", is_approved: false },
  { tool_name: "AI21 Labs", domain: "studio.ai21.com", category: "ai platform", vendor: "AI21 Labs", risk_level: "medium", is_approved: false },
  { tool_name: "Writer", domain: "writer.com", category: "enterprise productivity", vendor: "Writer", risk_level: "medium", is_approved: true },
  { tool_name: "OpenRouter", domain: "openrouter.ai", category: "ai platform", vendor: "OpenRouter", risk_level: "high", is_approved: false },
  { tool_name: "GitHub Copilot", domain: "github.com", category: "development", vendor: "Microsoft", risk_level: "low", is_approved: true, cost_per_seat: 19 },
  { tool_name: "Cursor AI", domain: "cursor.sh", category: "development", vendor: "Anysphere", risk_level: "medium", is_approved: false },
  { tool_name: "Codeium", domain: "codeium.com", category: "development", vendor: "Codeium", risk_level: "medium", is_approved: false },
  { tool_name: "Windsurf", domain: "windsurf.ai", category: "development", vendor: "Codeium", risk_level: "medium", is_approved: false },
  { tool_name: "Tabnine", domain: "tabnine.com", category: "development", vendor: "Tabnine", risk_level: "medium", is_approved: true, cost_per_seat: 12, suggested_alternative: "GitHub Copilot" },
  { tool_name: "Replit AI", domain: "replit.com", category: "development", vendor: "Replit", risk_level: "medium", is_approved: false },
  { tool_name: "Hugging Face", domain: "huggingface.co", category: "development", vendor: "HuggingFace", risk_level: "medium", is_approved: false },
  { tool_name: "HuggingFace Spaces", domain: "spaces.huggingface.co", category: "ai platform", vendor: "HuggingFace", risk_level: "medium", is_approved: false },
  { tool_name: "Continue.dev", domain: "continue.dev", category: "development", vendor: "Continue", risk_level: "medium", is_approved: false },
  { tool_name: "Sourcegraph Cody", domain: "sourcegraph.com", category: "development", vendor: "Sourcegraph", risk_level: "medium", is_approved: true },
  { tool_name: "Supermaven", domain: "supermaven.com", category: "development", vendor: "Supermaven", risk_level: "medium", is_approved: false },
  { tool_name: "Pieces for Developers", domain: "app.pieces.app", category: "development", vendor: "Pieces", risk_level: "medium", is_approved: true },
  { tool_name: "Blackbox AI", domain: "www.blackbox.ai", category: "development", vendor: "Blackbox AI", risk_level: "medium", is_approved: false },
  { tool_name: "Phind", domain: "phind.com", category: "development", vendor: "Phind", risk_level: "medium", is_approved: false },
  { tool_name: "Zed Editor", domain: "zed.dev", category: "development", vendor: "Zed Industries", risk_level: "medium", is_approved: false },
  { tool_name: "Bolt.new", domain: "bolt.new", category: "development", vendor: "StackBlitz", risk_level: "medium", is_approved: false },
  { tool_name: "Vercel V0", domain: "v0.dev", category: "development", vendor: "Vercel", risk_level: "medium", is_approved: false },
  { tool_name: "Lovable", domain: "lovable.dev", category: "development", vendor: "Lovable", risk_level: "medium", is_approved: false },
  { tool_name: "Same.dev", domain: "same.dev", category: "development", vendor: "Same", risk_level: "medium", is_approved: false },
  { tool_name: "Portkey", domain: "portkey.ai", category: "ai platform", vendor: "Portkey", risk_level: "medium", is_approved: true },
  { tool_name: "Helicone", domain: "helicone.ai", category: "ai observability", vendor: "Helicone", risk_level: "medium", is_approved: true },
  { tool_name: "Pinecone", domain: "pinecone.io", category: "vector db", vendor: "Pinecone", risk_level: "medium", is_approved: true },
  { tool_name: "Qdrant Cloud", domain: "cloud.qdrant.io", category: "vector db", vendor: "Qdrant", risk_level: "medium", is_approved: true },
  { tool_name: "Zilliz Cloud (Milvus)", domain: "zilliz.com", category: "vector db", vendor: "Zilliz", risk_level: "medium", is_approved: true },
  { tool_name: "Modal", domain: "modal.com", category: "ai platform", vendor: "Modal", risk_level: "medium", is_approved: false },
  { tool_name: "Gradio / HuggingFace Spaces", domain: "gradio.app", category: "ai platform", vendor: "HuggingFace", risk_level: "medium", is_approved: false },
  { tool_name: "Weights & Biases", domain: "wandb.ai", category: "ai platform", vendor: "W&B", risk_level: "medium", is_approved: true },
  { tool_name: "Scale AI", domain: "scale.com", category: "ai platform", vendor: "Scale AI", risk_level: "medium", is_approved: true },
  { tool_name: "Labelbox", domain: "labelbox.com", category: "ai platform", vendor: "Labelbox", risk_level: "medium", is_approved: true },
  { tool_name: "Lightning AI", domain: "lightning.ai", category: "ai platform", vendor: "Lightning AI", risk_level: "medium", is_approved: false },
  { tool_name: "Braintrust", domain: "braintrust.dev", category: "ai observability", vendor: "Braintrust", risk_level: "medium", is_approved: true },
  { tool_name: "HoneyHive", domain: "app.honeyhive.ai", category: "ai observability", vendor: "HoneyHive", risk_level: "medium", is_approved: true },
  { tool_name: "Traceloop", domain: "traceloop.com", category: "ai observability", vendor: "Traceloop", risk_level: "medium", is_approved: true },
  { tool_name: "Langfuse", domain: "cloud.langfuse.com", category: "ai observability", vendor: "Langfuse", risk_level: "medium", is_approved: true },
  { tool_name: "Arize Phoenix", domain: "phoenix.arize.com", category: "ai observability", vendor: "Arize AI", risk_level: "medium", is_approved: true },
  { tool_name: "Midjourney", domain: "midjourney.com", category: "design/media", vendor: "Midjourney", risk_level: "medium", is_approved: false, cost_per_seat: 30, suggested_alternative: "DALL-E" },
  { tool_name: "Stable Diffusion", domain: "stability.ai", category: "design/media", vendor: "Stability AI", risk_level: "medium", is_approved: false },
  { tool_name: "Adobe Firefly", domain: "firefly.adobe.com", category: "design/media", vendor: "Adobe", risk_level: "medium", is_approved: true },
  { tool_name: "Ideogram", domain: "ideogram.ai", category: "design/media", vendor: "Ideogram", risk_level: "medium", is_approved: false },
  { tool_name: "GetImg.ai", domain: "getimg.ai", category: "design/media", vendor: "GetImg", risk_level: "medium", is_approved: false },
  { tool_name: "NightCafe", domain: "creator.nightcafe.studio", category: "design/media", vendor: "NightCafe", risk_level: "medium", is_approved: false },
  { tool_name: "Leonardo.ai", domain: "leonardo.ai", category: "design/media", vendor: "Leonardo", risk_level: "medium", is_approved: false },
  { tool_name: "Runway", domain: "runway.ml", category: "video ai", vendor: "Runway", risk_level: "medium", is_approved: false },
  { tool_name: "Pika Labs", domain: "pika.art", category: "video ai", vendor: "Pika Labs", risk_level: "medium", is_approved: false },
  { tool_name: "Luma Dream Machine", domain: "lumalabs.ai", category: "video ai", vendor: "Luma AI", risk_level: "medium", is_approved: false },
  { tool_name: "Synthesia", domain: "synthesia.io", category: "video ai", vendor: "Synthesia", risk_level: "medium", is_approved: false },
  { tool_name: "HeyGen", domain: "heygen.com", category: "video ai", vendor: "HeyGen", risk_level: "medium", is_approved: false },
  { tool_name: "D-ID", domain: "d-id.com", category: "video ai", vendor: "D-ID", risk_level: "medium", is_approved: false },
  { tool_name: "HailuoAI (Minimax)", domain: "hailuoai.com", category: "video ai", vendor: "Minimax", risk_level: "high", is_approved: false },
  { tool_name: "Kling AI", domain: "klingai.com", category: "video ai", vendor: "Kuaishou", risk_level: "high", is_approved: false },
  { tool_name: "InVideo AI", domain: "invideo.io", category: "video ai", vendor: "InVideo", risk_level: "medium", is_approved: false },
  { tool_name: "ElevenLabs", domain: "elevenlabs.io", category: "audio ai", vendor: "ElevenLabs", risk_level: "medium", is_approved: false },
  { tool_name: "Suno AI", domain: "suno.ai", category: "audio ai", vendor: "Suno", risk_level: "medium", is_approved: false },
  { tool_name: "Udio", domain: "udio.com", category: "audio ai", vendor: "Udio", risk_level: "medium", is_approved: false },
  { tool_name: "Deepgram", domain: "deepgram.com", category: "audio ai", vendor: "Deepgram", risk_level: "medium", is_approved: true },
  { tool_name: "AssemblyAI", domain: "assemblyai.com", category: "audio ai", vendor: "AssemblyAI", risk_level: "medium", is_approved: true },
  { tool_name: "Murf AI", domain: "murf.ai", category: "audio ai", vendor: "Murf", risk_level: "medium", is_approved: true },
  { tool_name: "Notion AI", domain: "notion.so", category: "productivity", vendor: "Notion", risk_level: "low", is_approved: true },
  { tool_name: "Grammarly", domain: "grammarly.com", category: "writing", vendor: "Grammarly", risk_level: "low", is_approved: true },
  { tool_name: "Canva Magic Studio", domain: "canva.com", category: "design/media", vendor: "Canva", risk_level: "low", is_approved: false },
  { tool_name: "Otter.ai", domain: "otter.ai", category: "productivity", vendor: "Otter", risk_level: "medium", is_approved: false },
  { tool_name: "Fireflies.ai", domain: "fireflies.ai", category: "productivity", vendor: "Fireflies", risk_level: "medium", is_approved: false },
  { tool_name: "Jasper AI", domain: "app.jasper.ai", category: "writing", vendor: "Jasper", risk_level: "medium", is_approved: true },
  { tool_name: "Writesonic", domain: "writesonic.com", category: "writing", vendor: "Writesonic", risk_level: "medium", is_approved: false },
  { tool_name: "Copy.ai", domain: "copy.ai", category: "writing", vendor: "Copy.ai", risk_level: "medium", is_approved: false },
  { tool_name: "Rytr", domain: "rytr.me", category: "writing", vendor: "Rytr", risk_level: "medium", is_approved: false },
  { tool_name: "Wordtune", domain: "wordtune.com", category: "writing", vendor: "AI21 Labs", risk_level: "medium", is_approved: false },
  { tool_name: "Fathom AI Notetaker", domain: "fathom.video", category: "productivity", vendor: "Fathom", risk_level: "medium", is_approved: false },
  { tool_name: "tl;dv", domain: "tldv.io", category: "productivity", vendor: "tl;dv", risk_level: "medium", is_approved: false },
  { tool_name: "Read.ai", domain: "read.ai", category: "productivity", vendor: "Read", risk_level: "medium", is_approved: true },
  { tool_name: "MeetGeek", domain: "meetgeek.ai", category: "productivity", vendor: "MeetGeek", risk_level: "medium", is_approved: false },
  { tool_name: "Avoma", domain: "avoma.com", category: "productivity", vendor: "Avoma", risk_level: "medium", is_approved: true },
  { tool_name: "Jamie AI", domain: "jamie.ai", category: "productivity", vendor: "Jamie", risk_level: "medium", is_approved: false },
  { tool_name: "You.com AI Search", domain: "you.com", category: "chat", vendor: "You.com", risk_level: "medium", is_approved: false },
  { tool_name: "Kagi AI", domain: "kagi.com", category: "chat", vendor: "Kagi", risk_level: "medium", is_approved: false },
  { tool_name: "Hex", domain: "hex.tech", category: "ai platform", vendor: "Hex", risk_level: "medium", is_approved: true },
  { tool_name: "Julius AI", domain: "julius.ai", category: "ai platform", vendor: "Julius", risk_level: "medium", is_approved: false },
  { tool_name: "Gamma", domain: "gamma.app", category: "productivity", vendor: "Gamma", risk_level: "low", is_approved: false }
];

export const categories = [...new Set(aiToolsRegistry.map(t => t.category))];
export const vendors = [...new Set(aiToolsRegistry.map(t => t.vendor))];
export const riskLevels: AITool["risk_level"][] = ["low", "medium", "high"];
